version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_DATABASE: springboot
      MYSQL_ROOT_PASSWORD: root1234  # Empty password for root user
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql"]  # Use container name 'mysql' here
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""  # No password
    ports:
      - "8081:80"
    depends_on:
      - mysql

  springboot_app:
    build: .
    container_name: crud_springboot_project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: springboot
      MYSQL_USER: root
      MYSQL_PASSWORD: ""  # Empty password for the Spring Boot app
    volumes:
      - C:/Users/rutvi/IdeaProjects/crud/crud:/app  # Correct Windows path handling for volume mount
    ports:
      - "8082:8080"
    depends_on:
      - mysql
