version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_DATABASE: springboot
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8081:80"
    depends_on:
      - mysql

  springboot_app:
    build: .
    container_name: crud_springboot_project
    environment:
      SERVER_PORT: 8080
      SERVER_ADDRESS: 0.0.0.0
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: springboot
      MYSQL_USER: root
      MYSQL_PASSWORD: ""
    ports:
      - "8082:8080"
    depends_on:
      - mysql
